### ISSUE TITLE
Issues with Interlink

### ISSUE THREAD

**Issue by mattatobin** [RealRaven2000/menu-on-top#1]
This extension has no real reason to target Interlink.. `messenger.xul` already has the menubar on top. Indeed several structural changes happened in the course of it's development. All this extension does is bust the UI slightly.

Please consider removing the Thunderbird `em:targetApplication` in your next update.

**Comment by RealRaven2000** [comment]
I have fixed the bustage today - the description (lifting the menubar back up top) is a little outdated - try version 1.13. What MenuOnTop does is add a lot customization to the main menu which is especially handy if you're (like me) using many XUL applications and different versions (I often run 3 different Thunderbird versions at the same time) - this makes each app look sufficiently different. Also I added a mini "bookmarks" menu (If you activate custom menu) in which you can bookmark any email, contentTab.about pages such as about:config, and any arbitrary web page. Again this is more useful for mail developers but I can imagine uses for ordinary users, too. By the way the menu can also display the current remote port, which will be useful once Interlink fixes the remote debugger socket.

Finally I do not want to remove Thunderbird as targetApplication as this would mean I have to fork the code. This version runs quite happily on Thunderbird 52 - 66 and is extremely useful there!

**Comment by RealRaven2000** [comment]
Here is an example on how I use MenuOnTop:
http://quickfolders.org/images/menuOnTop/applications-example.png

**Comment by mattatobin** [comment]
Well as long as it takes into account the fact that Interlink isn't the same as Thunderbird then I suppose that is great.

I thought perhaps it was an oversight like many Pale Moon extensions never removed their Firefox and Thunderbird `targetApplication` blocks because laziness when they most certainly don't work correctly with them out of the box. Which with our multi-application targeting add-ons site software is a problem.

In any event, thank you for your support of Interlink Mail & News specifically!

**Comment by RealRaven2000** [comment]
> Well as long as it takes into account the fact that Interlink isn't the same as Thunderbird then that is great.
> 
> I thought perhaps it was an oversight like many Pale Moon extensions never removed their Firefox and Thunderbird `targetApplication` blocks because laziness when they most certainly don't work correctly with them out of the box. Which with our multi-application targeting add-ons site software is a problem.
> 
Yes - to be quite honest I had trouble running Interlink at first (it woudln't start until I shut down all my Thunderbird instances). Only then I discovered how badly my Add-ons behave. Having said that they were working on older versions of thunderbird (and Postbox!) so it shouldn't be too difficult to adapt them.

> > By the way the menu can also display the current remote port, which will be useful once Interlink fixes the remote debugger socket.
> 
> There is nothing to fix. Interlink does NOT support the Mozilla Developer Tools and never will.
Well maybe I will find a version of Venkman that works then. In the meantime it's back to the old "look at error console", fix, install, restart cycle. I have done it a million times so I am well used to it :)

I am still yet to test how well QuickPasswords works on Interlink - again it works well in Thunderbird and Waterfox.

Next project is going to be adapting quickFilters and SmartTemplate⁴. Shouldn't be too hard.

**Comment by mattatobin** [comment]
Working well in non-UXP applications is no indication of anything when it comes to extensions. Extensions have to be made compatible with the application at hand.

Won't matter in the long term I guess as UXP will be the last man standing when it comes to XUL technology. You can trust that.
