### ISSUE TITLE
Check version 78.* and update the Plugin Menu on top

### ISSUE THREAD

**Issue by blackcrack** [RealRaven2000/menu-on-top#4]
Check version 78.* and update the Plugin Menu on top
![445196-64](https://user-images.githubusercontent.com/7925717/125153035-694a2700-e151-11eb-9a20-216613fba1dd.jpg)

![Screen 00007](https://user-images.githubusercontent.com/7925717/125153140-06a55b00-e152-11eb-8e32-7925fff2b9f8.jpg)
![Screen 00006](https://user-images.githubusercontent.com/7925717/125153142-0907b500-e152-11eb-86c7-0c93683de686.jpg)

**Comment by RealRaven2000** [comment]
There is a process of converting a Legacy Bootstrap WebExtension into a MailExtension for Thunderbird 78, the instructions can be found here:

https://github.com/thundernest/addon-developer-support/wiki/Using-the-BootstrapLoader-API-to-convert-a-Legacy-Bootstrap-WebExtension-into-a-MailExtension-for-Thunderbird-78

If you can get the process started I can probably assist, just don't have the time to do it myself.

**Comment by RealRaven2000** [comment]
Further reading on mail extensions (leave that one for later unless you need to look up something fundamental)
https://developer.thunderbird.net/add-ons/mailextensions
